# Generated by Django 6.0.4 on 2026-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stash',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('S', 'Saved'), ('I', 'Interview'), ('O', 'Offer'), ('R', 'Rejected')], default='S', max_length=1),
        ),
    ]
